# -*- mode: ruby -*-
# vi: set ft=ruby :
ENV['VAGRANT_NO_PARALLEL'] = 'yes'
Vagrant.configure(2) do |config|
  NodeCount = 2
  (1..NodeCount).each do |i|
    config.vm.define "servidorUbuntu0#{i}" do |node|
      node.vm.box = "bento/ubuntu-20.04"
      node.vm.hostname = "servidorubuntu0#{i}.example.com"
      node.vm.network "private_network", ip: "192.168.100.1#{i}"
      node.vm.provision "shell" , path: "script.sh"
      node.vm.provider "virtualbox" do |v|
        v.name = "servidorUbuntu0#{i}"
        v.memory = 1024
        v.cpus = 1
      end
    end
  end
  config.vm.define :servidorHaproxy do |haproxyNode|
    haproxyNode.vm.box = "bento/ubuntu-20.04"
    haproxyNode.vm.network :"private_network", ip: "192.168.100.13"
    haproxyNode.vm.provision "shell", path: "haproxy.sh"
    haproxyNode.vm.provider "virtualbox" do |vproxy|
      vproxy.name = "servidorHaproxy"
      vproxy.memory = 1024
      vproxy.cpus = 1
    end
  end

end
