# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
    config.vm.define :servidorUbuntu do |servidorUbuntu|
        servidorUbuntu.vm.box = "bento/ubuntu-20.04"
        servidorUbuntu.vm.network :private_network, ip: "192.168.100.5"
        servidorUbuntu.vm.hostname = "machine1"
    end
    config.vm.define :clienteUbuntu do |clienteUbuntu|
        clienteUbuntu.vm.box = "bento/ubuntu-20.04"
        clienteUbuntu.vm.network :private_network, ip: "192.168.100.6"
        clienteUbuntu.vm.hostname = "machineGuest"
    end
end