# -*- mode: ruby -*-
# vi: set ft=ruby :

$install_puppet = <<-PUPPET
sudo apt-get install -y puppet
PUPPET

Vagrant.configure("2") do |config|
    config.vm.define :clienteUbuntu do |clienteUbuntu|
    clienteUbuntu.vm.box = "bento/ubuntu-20.04"
    clienteUbuntu.vm.network :private_network, ip: "192.168.100.2"
    clienteUbuntu.vm.hostname = "clienteUbuntu"
  end
    config.vm.define :servidorUbuntu do |servidorUbuntu|
    servidorUbuntu.vm.box = "bento/ubuntu-20.04"
    servidorUbuntu.vm.network :private_network, ip: "192.168.100.3"
    servidorUbuntu.vm.provision "shell" , path: "script.sh"
    servidorUbuntu.vm.hostname = "servidorUbuntu"
  end
    config.vm.box = "bento/ubuntu-20.04"
    config.vm.hostname = "puppetServer"
    config.vm.network :private_network, ip: "192.168.90.3"
    config.vm.provision "shell", inline: $install_puppet
    config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "testPuppet/puppet/manifests"
    puppet.manifest_file = "site.pp"
    puppet.module_path = "testPuppet/puppet/modules"
  end
end
