Vagrant.configure("2") do |config|
      config.vm.define :ftpUbuntu do |ftpUbuntu|
      ftpUbuntu.vm.box = "bento/ubuntu-20.04"
      ftpUbuntu.vm.network :private_network, ip: "192.168.90.4"
      ftpUbuntu.vm.provision "shell" , path: "script.sh"
      config.vm.synced_folder "ftpFiles/", "/home/vagrant/filesFtp"
      ftpUbuntu.vm.hostname = "ftpUbuntu"
    end
end