version: "3"
services:
  vsftpd:
    image: panubo/vsftpd
    environment:
      - FTP_USER=milmax
      - FTP_PASSWORD=duque
    volumes:
      - /vagrant/arcvhivos:/home/vagrant/ftp_dockerCompose/files
    expose:
      - 21
    network_mode: host